### ISSUE TITLE
docker issue

### ISSUE THREAD

**Issue by luxigo** [doxel/doxel-docker#1]
Using gnu screen 4.05 and docker version 17.06.2-ce build cec0b72 on debian stable (stretch)

When running  `screen -S doxel -dm bash -l -c "docker run -it doxel/dev ; exec bash"`, the docker container standard output does not appear in screen tab 0  (it does when the container is launched from a terminal)

And  opening a shell from a screen tab with eg `docker exec -itu root doxel /bin/bash` exits immediately with code 0

Everything works fine with Docker version 17.05.0-ce, build 89658be and Docker version 17.03.2-ce, build f5ec1e2

**Comment by bugdanov** [comment]
fixed by updating to Docker version 17.09.0-ce, build afdb6d4
